services:
  order-lifecycle:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/orders
      SQLX_OFFLINE: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d orders']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:

networks:
  default:
    name: order-lifecycle
